export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/*<script async src="https://cdn.jsdelivr.net/pyodide/v0.22.1/full/pyodide.js" />*/}
    </>
  );
}
